In [1]:
import pandas as pd
import numpy as np

In [2]:
# 欧式看涨期权二叉树
def binarytree_eurocall(S,K,r,T,sigma=None,q=0,steps=2,ud=None):

    '''
    S:标的资产初始价格;
    K:期权的执行价格;
    r:年化无风险利率;
    q:连续分红的红利率,默认不分红;
    sigma:标的资产连续复利收益率的标准差;
    T:以年表示的时间长度;
    steps:二叉树的步长
    '''
    t = T/steps   # 每一步的期间长度
    if ud == None:
        u = np.exp(sigma*np.sqrt(t))  # 上行乘数
        d = 1/u  # 下行乘数
    else:
        u = ud[0]
        d = ud[1]
    P = (np.exp((r-q)*t)-d)/(u-d)  # 股价上行的风险中性概率
    print('风险中性概率为:',P)
    stock_prices = np.zeros(shape=(steps+1,steps+1)) # 生成最后一列的股票价格空数组
    stock_prices[0][0] = S
    for i in range(1,steps+1):
        for j in range(0,i+1):
            stock_prices[j][i] = S*pow(u,i-j)*pow(d,j)
    print('股价二叉树:')
    print(stock_prices)
    option_prices = np.zeros(shape=(steps+1,steps+1))
    option_prices[:,-1] = list(map(lambda x:max(x,0),stock_prices[:,-1]-K))  # 到期日价值
    for i in range(steps-1,-1,-1):
        for j in range(0,i+1):
            option_prices[j][i] = np.exp(-(r-q)*t)*(P*option_prices[j,i+1]+(1-P)*option_prices[j+1,i+1])
    print('期权二叉树:')
    print(option_prices)
    print('根据%d期二叉树模型确定的欧式看涨期权价格为%.2f'%(steps,option_prices[0][0]))

In [3]:
binarytree_eurocall(S=980,K=1000,r=0.006,sigma=0.2,T=0.5,q=0,steps=1,ud=[1200/980,720/980])

风险中性概率为: 0.5478008633610615
股价二叉树:
[[ 980. 1200.]
 [   0.  720.]]
期权二叉树:
[[109.23198468 200.        ]
 [  0.           0.        ]]
根据1期二叉树模型确定的欧式看涨期权价格为109.23


In [4]:
# 欧式看跌期权二叉树
def binarytree_europut(S,K,r,T,sigma=None,q=0,steps=2,ud=None):

    '''
    S:标的资产初始价格;
    K:期权的执行价格;
    r:年化无风险利率;
    q:连续分红的红利率,默认不分红;
    sigma:标的资产连续复利收益率的标准差;
    T:以年表示的时间长度;
    steps:二叉树的步长
    '''
    t = T/steps   # 每一步的期间长度
    if ud == None:
        u = np.exp(sigma*np.sqrt(t))  # 上行乘数
        d = 1/u  # 下行乘数
    else:
        u = ud[0]
        d = ud[1]
    P = (np.exp((r-q)*t)-d)/(u-d)  # 股价上行的风险中性概率
    print('风险中性概率为:',P)
    stock_prices = np.zeros(shape=(steps+1,steps+1)) # 生成最后一列的股票价格空数组
    stock_prices[0][0] = S
    for i in range(1,steps+1):
        for j in range(0,i+1):
            stock_prices[j][i] = S*pow(u,i-j)*pow(d,j)
    print('股价二叉树:')
    print(stock_prices)
    option_prices = np.zeros(shape=(steps+1,steps+1))
    option_prices[:,-1] = list(map(lambda x:max(x,0),K-stock_prices[:,-1]))  # 到期日价值
    for i in range(steps-1,-1,-1):
        for j in range(0,i+1):
            option_prices[j][i] = np.exp(-(r-q)*t)*(P*option_prices[j,i+1]+(1-P)*option_prices[j+1,i+1])
    print('期权二叉树:')
    print(option_prices)
    print('根据%d期二叉树模型确定的欧式看跌期权价格为%.2f'%(steps,option_prices[0][0]))

In [6]:
binarytree_europut(S=100,K=105,r=0.05,T=2,q=0,steps=2,ud=[1.12,0.88])

风险中性概率为: 0.7136295682334335
股价二叉树:
[[100.   112.   125.44]
 [  0.    88.    98.56]
 [  0.     0.    77.44]]
期权二叉树:
[[ 4.4267623   1.75428164  0.        ]
 [ 0.         11.87908957  6.44      ]
 [ 0.          0.         27.56      ]]
根据2期二叉树模型确定的欧式看跌期权价格为4.43


In [40]:
# 美式看涨期权二叉树
def binarytree_Americancall(S,K,r,T,sigma=None,q=0,steps=2,ud=None):

    '''
    S:标的资产初始价格;
    K:期权的执行价格;
    r:年化无风险利率;
    q:连续分红的红利率,默认不分红;
    sigma:标的资产连续复利收益率的标准差;
    T:以年表示的时间长度;
    steps:二叉树的步长
    '''
    t = T/steps   # 每一步的期间长度
    if ud == None:
        u = np.exp(sigma*np.sqrt(t))  # 上行乘数
        d = 1/u  # 下行乘数
    else:
        u = ud[0]
        d = ud[1]
    P = (np.exp((r-q)*t)-d)/(u-d)  # 股价上行的风险中性概率
    print('风险中性概率为:',P)
    stock_prices = np.zeros(shape=(steps+1,steps+1)) # 生成最后一列的股票价格空数组
    stock_prices[0][0] = S
    for i in range(1,steps+1):
        for j in range(0,i+1):
            stock_prices[j][i] = S*pow(u,i-j)*pow(d,j)
    print('股价二叉树:')
    print(stock_prices)
    option_prices = np.zeros(shape=(steps+1,steps+1))
    option_prices[:,-1] = list(map(lambda x:max(x,0),stock_prices[:,-1]-K))  # 到期日价值
    for i in range(steps-1,-1,-1):
        for j in range(0,i+1):
            discount_value = np.exp(-(r-q)*t)*(P*option_prices[j,i+1]+(1-P)*option_prices[j+1,i+1])
            current_value  = max(0,stock_prices[j][i]-K)
            option_prices[j][i] = max(discount_value,current_value)
    print('期权二叉树:')
    print(option_prices)
    print('根据%d期二叉树模型确定的美式看涨期权价格为%.2f'%(steps,option_prices[0][0]))

In [ ]:
binarytree_Americancall(S,K,r,T,sigma=None,q=0,steps=2,ud=None)

In [41]:
def binarytree_Americanput(S,K,r,T,sigma=None,q=0,steps=2,ud=None):

    '''
    S:标的资产初始价格;
    K:期权的执行价格;
    r:年化无风险利率;
    q:连续分红的红利率,默认不分红;
    sigma:标的资产连续复利收益率的标准差;
    T:以年表示的时间长度;
    steps:二叉树的步长
    '''
    t = T/steps   # 每一步的期间长度
    if ud == None:
        u = np.exp(sigma*np.sqrt(t))  # 上行乘数
        d = 1/u  # 下行乘数
    else:
        u = ud[0]
        d = ud[1]
    P = (np.exp((r-q)*t)-d)/(u-d)  # 股价上行的风险中性概率
    print('风险中性概率为:',P)
    stock_prices = np.zeros(shape=(steps+1,steps+1)) # 生成最后一列的股票价格空数组
    stock_prices[0][0] = S
    for i in range(1,steps+1):
        for j in range(0,i+1):
            stock_prices[j][i] = S*pow(u,i-j)*pow(d,j)
    print('股价二叉树:')
    print(stock_prices)
    option_prices = np.zeros(shape=(steps+1,steps+1))
    option_prices[:,-1] = list(map(lambda x:max(x,0),K-stock_prices[:,-1]))  # 到期日价值
    for i in range(steps-1,-1,-1):
        for j in range(0,i+1):
            discount_value = np.exp(-(r-q)*t)*(P*option_prices[j,i+1]+(1-P)*option_prices[j+1,i+1])
            current_value  = max(0,K-stock_prices[j][i])
            option_prices[j][i] = max(discount_value,current_value)
    print('期权二叉树:')
    print(option_prices)
    print('根据%d期二叉树模型确定的美式看跌期权价格为%.2f'%(steps,option_prices[0][0]))

In [50]:
binarytree_Americanput(S=100,K=105,r=0.05,T=2,q=0,steps=2,ud=[1.12,0.88])

风险中性概率为: 0.7136295682334335
股价二叉树:
[[100.   112.   125.44]
 [  0.    88.    98.56]
 [  0.     0.    77.44]]
期权二叉树:
[[ 5.82171869  1.75428164  0.        ]
 [ 0.         17.          6.44      ]
 [ 0.          0.         27.56      ]]
根据2期二叉树模型确定的美式看跌期权价格为5.82
